-- =============================================================================
-- install_external_ml.sql
--
-- ONE-TIME, MANUAL install step. Run this once, as ACCOUNTADMIN (or any role
-- with IMPORTED PRIVILEGES ON SNOWFLAKE DB), in the SAME account where the
-- "ML Behavioral Anomaly Detection" Native App is installed.
--
-- WHY THIS EXISTS (do not skip this step, and do not try to move this logic
-- into the app): SNOWFLAKE.ML.ANOMALY_DETECTION objects are "Class" objects,
-- and Snowflake's Native App Framework does not support creating Class
-- objects inside an application's own database ("Classes are not supported
-- in an application" -- confirmed empirically against a real account, not
-- assumed). This is the ONLY part of the whole system that cannot live
-- inside the Native App. Everything else -- correlation/scoring, Cortex AI
-- narratives, the Trust Center scanner callback, the dashboard UI -- lives
-- entirely inside the app and requires zero manual SQL.
--
-- This script is intentionally minimal: it creates ONLY the 20 ML models,
-- ONE wrapper procedure the app calls via a Native App reference, and the
-- weekly retrain task. There are no separate view objects -- each model's
-- training query and each detection call use an inline subquery, since
-- nothing else ever needs to query these views by name.
--
-- Every model is trained inside a per-model error-tolerant block: some
-- signals (e.g. AD_ROWS_UNLOADED, AD_OUTBOUND_TRANSFER) may have zero
-- matching rows over the last 90 days on quiet accounts or accounts that
-- don't use that particular feature -- that is expected and NOT a failure.
-- MODELS.train_all_models() reports exactly how many models trained vs.
-- were skipped, and the weekly retrain task re-attempts skipped signals
-- automatically once real activity shows up.
--
-- After running this script, go to the app's Setup page and complete the
-- final step: binding the app's reference to MODELS.RUN_DETECTION. See
-- README.md in this directory for the exact command.
-- =============================================================================

CREATE DATABASE IF NOT EXISTS ML_ANOMALY_EXTERNAL;
CREATE SCHEMA IF NOT EXISTS ML_ANOMALY_EXTERNAL.MODELS;
USE SCHEMA ML_ANOMALY_EXTERNAL.MODELS;

-- =============================================================================
-- 20 SNOWFLAKE.ML.ANOMALY_DETECTION models, trained on 90 days of history
-- (holding out the most recent 7 days so DETECT_ANOMALIES below has unseen
-- data to score against). Each INPUT_DATA is an inline subquery over
-- SNOWFLAKE.ACCOUNT_USAGE -- no separate view objects. Each CREATE MODEL
-- statement is wrapped in its own error-tolerant block below, so one empty
-- signal never blocks the other 19 from training.
-- =============================================================================

CREATE OR REPLACE PROCEDURE MODELS.train_all_models()
  RETURNS STRING
  LANGUAGE SQL
AS
$$
DECLARE
  trained INT DEFAULT 0;
  skipped INT DEFAULT 0;
  skipped_names VARCHAR DEFAULT '';
BEGIN
  -- Authentication
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_login_count(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, EVENT_TIMESTAMP::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
          WHERE IS_SUCCESS = 'YES' AND EVENT_TIMESTAMP >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, EVENT_TIMESTAMP::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_login_count ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_failed_auth(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, EVENT_TIMESTAMP::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
          WHERE IS_SUCCESS = 'NO' AND EVENT_TIMESTAMP >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, EVENT_TIMESTAMP::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_failed_auth ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_distinct_ips(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, EVENT_TIMESTAMP::DATE::TIMESTAMP_NTZ AS TS, COUNT(DISTINCT CLIENT_IP)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
          WHERE IS_SUCCESS = 'YES' AND EVENT_TIMESTAMP >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, EVENT_TIMESTAMP::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_distinct_ips ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_client_diversity(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, EVENT_TIMESTAMP::DATE::TIMESTAMP_NTZ AS TS, COUNT(DISTINCT REPORTED_CLIENT_TYPE)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
          WHERE IS_SUCCESS = 'YES' AND EVENT_TIMESTAMP >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, EVENT_TIMESTAMP::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_client_diversity ';
  END;
  -- Data Access/Exfiltration
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_query_volume(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_query_volume ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_bytes_scanned(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(BYTES_SCANNED)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_bytes_scanned ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_bytes_to_result(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(BYTES_WRITTEN_TO_RESULT)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_bytes_to_result ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_rows_unloaded(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(ROWS_UNLOADED)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND ROWS_UNLOADED > 0 AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_rows_unloaded ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_network_egress(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(BYTES_SENT_OVER_THE_NETWORK)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_network_egress ';
  END;
  -- Reconnaissance
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_db_breadth(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(DISTINCT DATABASE_NAME)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND DATABASE_NAME IS NOT NULL AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_db_breadth ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_table_breadth(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, QUERY_START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(DISTINCT f.value:"objectName"::STRING)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY, LATERAL FLATTEN(input => BASE_OBJECTS_ACCESSED) f
          WHERE f.value:"objectDomain"::STRING = 'Table' AND QUERY_START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, QUERY_START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_table_breadth ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_failed_queries(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS != 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_failed_queries ';
  END;
  -- Privilege Escalation
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_role_usage(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(DISTINCT ROLE_NAME)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_role_usage ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_ddl_operations(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS'
            AND QUERY_TYPE IN ('CREATE','CREATE_TABLE','CREATE_TABLE_AS_SELECT','CREATE_VIEW','CREATE_SCHEMA','CREATE_DATABASE','CREATE_ROLE','CREATE_USER','CREATE_STAGE','CREATE_PIPE','CREATE_TASK','CREATE_FUNCTION','CREATE_PROCEDURE','CREATE_NETWORK_POLICY','ALTER','ALTER_TABLE','ALTER_USER','ALTER_ROLE','ALTER_SCHEMA','ALTER_DATABASE','ALTER_NETWORK_POLICY','ALTER_ACCOUNT','DROP','DROP_TABLE','DROP_VIEW','DROP_SCHEMA','DROP_DATABASE','DROP_ROLE','DROP_USER','DROP_STAGE','GRANT','REVOKE')
            AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_ddl_operations ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_grant_operations(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND QUERY_TYPE IN ('GRANT','REVOKE') AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_grant_operations ';
  END;
  -- Insider Threat
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_data_staging(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND QUERY_TYPE = 'CREATE_TABLE_AS_SELECT' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_data_staging ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_outbound_transfer(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(OUTBOUND_DATA_TRANSFER_BYTES)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND OUTBOUND_DATA_TRANSFER_BYTES > 0 AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_outbound_transfer ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_ext_function_calls(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(EXTERNAL_FUNCTION_TOTAL_INVOCATIONS)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND EXTERNAL_FUNCTION_TOTAL_INVOCATIONS > 0 AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY USER_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_ext_function_calls ';
  END;
  -- Resource Abuse
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_warehouse_credits(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT WAREHOUSE_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(CREDITS_USED)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
          WHERE START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY WAREHOUSE_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_warehouse_credits ';
  END;
  BEGIN
    CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION MODELS.ad_warehouse_queries(
      INPUT_DATA => TABLE(
        SELECT SERIES, TS, METRIC_VALUE FROM (
          SELECT WAREHOUSE_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE
          FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
          WHERE EXECUTION_STATUS = 'SUCCESS' AND WAREHOUSE_NAME IS NOT NULL AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP())
          GROUP BY WAREHOUSE_NAME, START_TIME::DATE
        ) WHERE TS < DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ
      ),
      SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE',
      LABEL_COLNAME => '', CONFIG_OBJECT => {'ON_ERROR':'SKIP'});
    trained := trained + 1;
  EXCEPTION
    WHEN OTHER THEN
      skipped := skipped + 1;
      skipped_names := skipped_names || 'ad_warehouse_queries ';
  END;
  RETURN 'Trained ' || trained || ' of 20 models. ' ||
    IFF(skipped = 0, 'All signals have sufficient history in this account.',
        skipped || ' skipped (no matching activity for this signal in the last 90 days): ' || skipped_names);
END;
$$;

CREATE OR REPLACE PROCEDURE MODELS.run_detection(run_id VARCHAR)
  RETURNS TABLE(model_name VARCHAR, series VARCHAR, ts TIMESTAMP_NTZ, y FLOAT, forecast FLOAT, lower_bound FLOAT, upper_bound FLOAT, is_anomaly BOOLEAN, percentile FLOAT, distance FLOAT)
  LANGUAGE SQL
AS
$$
DECLARE
  res RESULTSET;
BEGIN
  CREATE OR REPLACE TEMPORARY TABLE _raw (model_name VARCHAR, series VARCHAR, ts TIMESTAMP_NTZ, y FLOAT, forecast FLOAT, lower_bound FLOAT, upper_bound FLOAT, is_anomaly BOOLEAN, percentile FLOAT, distance FLOAT);

  BEGIN INSERT INTO _raw SELECT 'ad_login_count', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_login_count!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, EVENT_TIMESTAMP::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY WHERE IS_SUCCESS = 'YES' AND EVENT_TIMESTAMP >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, EVENT_TIMESTAMP::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_failed_auth', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_failed_auth!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, EVENT_TIMESTAMP::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY WHERE IS_SUCCESS = 'NO' AND EVENT_TIMESTAMP >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, EVENT_TIMESTAMP::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_distinct_ips', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_distinct_ips!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, EVENT_TIMESTAMP::DATE::TIMESTAMP_NTZ AS TS, COUNT(DISTINCT CLIENT_IP)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY WHERE IS_SUCCESS = 'YES' AND EVENT_TIMESTAMP >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, EVENT_TIMESTAMP::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_client_diversity', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_client_diversity!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, EVENT_TIMESTAMP::DATE::TIMESTAMP_NTZ AS TS, COUNT(DISTINCT REPORTED_CLIENT_TYPE)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY WHERE IS_SUCCESS = 'YES' AND EVENT_TIMESTAMP >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, EVENT_TIMESTAMP::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_query_volume', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_query_volume!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_bytes_scanned', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_bytes_scanned!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(BYTES_SCANNED)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_bytes_to_result', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_bytes_to_result!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(BYTES_WRITTEN_TO_RESULT)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_rows_unloaded', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_rows_unloaded!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(ROWS_UNLOADED)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND ROWS_UNLOADED > 0 AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_network_egress', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_network_egress!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(BYTES_SENT_OVER_THE_NETWORK)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_db_breadth', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_db_breadth!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(DISTINCT DATABASE_NAME)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND DATABASE_NAME IS NOT NULL AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_table_breadth', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_table_breadth!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, QUERY_START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(DISTINCT f.value:"objectName"::STRING)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY, LATERAL FLATTEN(input => BASE_OBJECTS_ACCESSED) f WHERE f.value:"objectDomain"::STRING = 'Table' AND QUERY_START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, QUERY_START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_failed_queries', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_failed_queries!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS != 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_role_usage', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_role_usage!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(DISTINCT ROLE_NAME)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_ddl_operations', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_ddl_operations!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND QUERY_TYPE IN ('CREATE','CREATE_TABLE','CREATE_TABLE_AS_SELECT','CREATE_VIEW','CREATE_SCHEMA','CREATE_DATABASE','CREATE_ROLE','CREATE_USER','CREATE_STAGE','CREATE_PIPE','CREATE_TASK','CREATE_FUNCTION','CREATE_PROCEDURE','CREATE_NETWORK_POLICY','ALTER','ALTER_TABLE','ALTER_USER','ALTER_ROLE','ALTER_SCHEMA','ALTER_DATABASE','ALTER_NETWORK_POLICY','ALTER_ACCOUNT','DROP','DROP_TABLE','DROP_VIEW','DROP_SCHEMA','DROP_DATABASE','DROP_ROLE','DROP_USER','DROP_STAGE','GRANT','REVOKE') AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_grant_operations', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_grant_operations!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND QUERY_TYPE IN ('GRANT','REVOKE') AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_data_staging', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_data_staging!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND QUERY_TYPE = 'CREATE_TABLE_AS_SELECT' AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_outbound_transfer', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_outbound_transfer!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(OUTBOUND_DATA_TRANSFER_BYTES)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND OUTBOUND_DATA_TRANSFER_BYTES > 0 AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_ext_function_calls', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_ext_function_calls!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT USER_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(EXTERNAL_FUNCTION_TOTAL_INVOCATIONS)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND EXTERNAL_FUNCTION_TOTAL_INVOCATIONS > 0 AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY USER_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_warehouse_credits', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_warehouse_credits!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT WAREHOUSE_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, SUM(CREDITS_USED)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY WHERE START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY WAREHOUSE_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;
  BEGIN INSERT INTO _raw SELECT 'ad_warehouse_queries', SERIES, TS, Y, FORECAST, LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE FROM TABLE(MODELS.ad_warehouse_queries!DETECT_ANOMALIES(INPUT_DATA => TABLE(SELECT SERIES, TS, METRIC_VALUE FROM (SELECT WAREHOUSE_NAME AS SERIES, START_TIME::DATE::TIMESTAMP_NTZ AS TS, COUNT(*)::FLOAT AS METRIC_VALUE FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY WHERE EXECUTION_STATUS = 'SUCCESS' AND WAREHOUSE_NAME IS NOT NULL AND START_TIME >= DATEADD('day', -97, CURRENT_TIMESTAMP()) GROUP BY WAREHOUSE_NAME, START_TIME::DATE) WHERE TS >= DATEADD('day',-7,CURRENT_DATE())::TIMESTAMP_NTZ), SERIES_COLNAME => 'SERIES', TIMESTAMP_COLNAME => 'TS', TARGET_COLNAME => 'METRIC_VALUE', CONFIG_OBJECT => {'prediction_interval':0.995})); EXCEPTION WHEN OTHER THEN NULL; END;

  res := (SELECT * FROM _raw);
  RETURN TABLE(res);
END;
$$;

-- The app's Native App role binds to this procedure via a reference (see
-- README.md) -- no GRANT to a Snowflake role is needed for that mechanism.

-- =============================================================================
-- MATERIALIZED RESULTS TABLE + refresh procedure.
--
-- IMPORTANT PLATFORM FINDING (confirmed against a real account): a Native
-- App's `reference()` function cannot invoke a stored PROCEDURE at all --
-- `CALL reference('x')(:arg)` is a syntax error (CALL does not accept a
-- reference() expression as its target), and `SELECT * FROM
-- TABLE(reference('x')(:arg))` resolves but fails with "Unknown table
-- function" for a PROCEDURE-type reference. Only TABLE/VIEW-type references
-- support the documented `SELECT * FROM reference('x')` query pattern.
--
-- So instead of the app calling MODELS.run_detection() live on every scan
-- (which also risks timing out Trust Center's scanner callback budget --
-- detecting across 20 models took several minutes in testing), this table
-- holds the LATEST detection run's raw rows, refreshed on a schedule below.
-- The app's reference points at this TABLE, not at the procedure.
-- =============================================================================

CREATE TABLE IF NOT EXISTS MODELS.detection_results (
  model_name VARCHAR, series VARCHAR, ts TIMESTAMP_NTZ, y FLOAT, forecast FLOAT,
  lower_bound FLOAT, upper_bound FLOAT, is_anomaly BOOLEAN, percentile FLOAT, distance FLOAT
);

CREATE OR REPLACE PROCEDURE MODELS.refresh_detection_results(run_id VARCHAR)
  RETURNS STRING
  LANGUAGE SQL
AS
$$
DECLARE
  det_res RESULTSET;
  row_count INT DEFAULT 0;
BEGIN
  det_res := (CALL MODELS.run_detection(:run_id));
  CREATE OR REPLACE TABLE MODELS.detection_results AS SELECT * FROM TABLE(det_res);
  row_count := (SELECT COUNT(*) FROM MODELS.detection_results);
  RETURN 'Refreshed detection_results: ' || row_count || ' rows.';
END;
$$;

-- =============================================================================
-- Weekly retraining task -- lives here (plain schema in a regular database),
-- not inside the app. Native Apps also cannot host TASK objects in a
-- versioned schema (confirmed separately), so keeping this external avoids
-- that constraint entirely in addition to the Class-object constraint.
-- Re-runs train_all_models(), which re-attempts any previously-skipped
-- signals in case the account now has matching activity.
-- =============================================================================

CREATE OR REPLACE TASK MODELS.ml_anomaly_retrain_task
  SCHEDULE = 'USING CRON 0 2 * * 0 UTC'
  COMMENT = 'Weekly retraining of all 20 ML anomaly detection models'
AS
CALL MODELS.train_all_models();

ALTER TASK MODELS.ml_anomaly_retrain_task RESUME;

-- Detection-refresh task: keeps MODELS.detection_results current for the app
-- to read via its TABLE reference, independent of the weekly retrain cadence.
CREATE OR REPLACE TASK MODELS.ml_anomaly_detect_task
  SCHEDULE = 'USING CRON 0 */6 * * * UTC'
  COMMENT = 'Refreshes detection_results every 6 hours for the Native App to read'
AS
CALL MODELS.refresh_detection_results(UUID_STRING());

ALTER TASK MODELS.ml_anomaly_detect_task RESUME;

-- Run the initial training now (also re-runnable any time by hand):
CALL MODELS.train_all_models();

-- Populate detection_results immediately so the app has data as soon as the
-- reference is bound, instead of waiting up to 6 hours for the first task run:
CALL MODELS.refresh_detection_results(UUID_STRING());
